export const BRANDS = [
    { id: 1, name: "Otra", logo: "" },
    { id: 2, name: "Volkswagen", logo: "https://logo.clearbit.com/vw.com" },
    { id: 3, name: "Ford", logo: "https://logo.clearbit.com/ford.com" },
    { id: 4, name: "Honda", logo: "https://logo.clearbit.com/honda.com" },
    { id: 5, name: "Chevrolet", logo: "https://logo.clearbit.com/chevrolet.com" },
    { id: 6, name: "Nissan", logo: "https://logo.clearbit.com/nissan.com" },
    { id: 7, name: "Hyundai", logo: "https://logo.clearbit.com/hyundai.com" },
    { id: 8, name: "Kia", logo: "https://logo.clearbit.com/kia.com" },
    { id: 9, name: "Mercedes-Benz", logo: "https://logo.clearbit.com/mercedes-benz.com" },
    { id: 10, name: "BMW", logo: "https://logo.clearbit.com/bmw.com" },
    { id: 11, name: "Audi", logo: "https://logo.clearbit.com/audi.com" },
    { id: 12, name: "Lexus", logo: "https://logo.clearbit.com/lexus.com" },
    { id: 13, name: "Tesla", logo: "https://logo.clearbit.com/tesla.com" },
    { id: 14, name: "Subaru", logo: "https://logo.clearbit.com/subaru.com" },
    { id: 15, name: "Mazda", logo: "https://logo.clearbit.com/mazda.com" },
    { id: 16, name: "Jeep", logo: "https://logo.clearbit.com/jeep.com" },
    { id: 17, name: "Volvo", logo: "https://logo.clearbit.com/volvocars.com" },
    { id: 18, name: "Porsche", logo: "https://logo.clearbit.com/porsche.com" },
    { id: 19, name: "Land Rover", logo: "https://logo.clearbit.com/landrover.com" },
    { id: 20, name: "Jaguar", logo: "https://logo.clearbit.com/jaguar.com" },
    { id: 21, name: "Peugeot", logo: "https://logo.clearbit.com/peugeot.com" },
    { id: 22, name: "Renault", logo: "https://logo.clearbit.com/renault.com" },
    { id: 23, name: "Fiat", logo: "https://logo.clearbit.com/fiat.com" },
    { id: 24, name: "Citroen", logo: "https://logo.clearbit.com/citroen.com" },
    { id: 25, name: "Mitsubishi", logo: "https://logo.clearbit.com/mitsubishi-motors.com" },
    { id: 26, name: "Suzuki", logo: "https://logo.clearbit.com/suzuki.com" },
    { id: 27, name: "GMC", logo: "https://logo.clearbit.com/gmc.com" },
    { id: 28, name: "Cadillac", logo: "https://logo.clearbit.com/cadillac.com" },
    { id: 29, name: "Ram", logo: "https://logo.clearbit.com/ramtrucks.com" },
    { id: 30, name: "Acura", logo: "https://logo.clearbit.com/acura.com" },
    { id: 31, name: "Infiniti", logo: "https://logo.clearbit.com/infinitiusa.com" },
    { id: 32, name: "Mini", logo: "https://logo.clearbit.com/miniusa.com" },
    { id: 33, name: "Alfa Romeo", logo: "https://logo.clearbit.com/alfaromeousa.com" },
    { id: 34, name: "Dodge", logo: "https://logo.clearbit.com/dodge.com" },
    { id: 35, name: "Chrysler", logo: "https://logo.clearbit.com/chrysler.com" },
    { id: 36, name: "Buick", logo: "https://logo.clearbit.com/buick.com" },
    { id: 37, name: "Skoda", logo: "https://logo.clearbit.com/skoda-auto.com" },
    { id: 38, name: "SEAT", logo: "https://logo.clearbit.com/seat.com" },
    { id: 39, name: "Toyota", logo: "https://logo.clearbit.com/toyota.com" },
];