// Colores comunes; siempre incluir "Otro" con id = 1
export const COLORS = [
  { id: 1, name: "Otro" },
  { id: 2, name: "Blanco" },
  { id: 3, name: "Negro" },
  { id: 4, name: "Gris" },
  { id: 5, name: "Plata" },
  { id: 6, name: "Rojo" },
  { id: 7, name: "Azul" },
  { id: 8, name: "Verde" },
  { id: 9, name: "Amarillo" },
  { id: 10, name: "Naranja" },
  { id: 11, name: "Café" },
  { id: 12, name: "Beige" },
  { id: 13, name: "Dorado" },
  { id: 14, name: "Morado" },
  { id: 15, name: "Azul Marino" },
  { id: 16, name: "Azul Oscuro" },
  { id: 17, name: "Rojo Vino" },
  { id: 18, name: "Verde Oscuro" },
  { id: 19, name: "Marrón" },
  { id: 20, name: "Crema" },
  { id: 21, name: "Blanco Perla" },
  { id: 22, name: "Negro Mate" },
  { id: 23, name: "Gris Grafito" },
  { id: 24, name: "Champán" },
  { id: 25, name: "Bronce" },
  { id: 26, name: "Cobre" },
  { id: 27, name: "Turquesa" },
];
