// Modelos por marca; cada lista incluye un "Otro" con id = 1
export const MODELS: Record<string, { id: number; name: string }[]> = {
    Otra: [{ id: 1, name: "Otro" }],
    Volkswagen: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Golf" },
        { id: 3, name: "Jetta" },
        { id: 4, name: "Tiguan" },
        { id: 5, name: "Passat" },
        { id: 6, name: "Amarok" },
        { id: 7, name: "Polo" },
        { id: 8, name: "T-Cross" },
        { id: 9, name: "Taos" },
    ],
    Ford: [
        { id: 1, name: "Otro" },
        { id: 2, name: "F-150" },
        { id: 3, name: "Ranger" },
        { id: 4, name: "Mustang" },
        { id: 5, name: "Escape" },
        { id: 6, name: "Explorer" },
        { id: 7, name: "Bronco" },
        { id: 8, name: "EcoSport" },
    ],
    Honda: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Civic" },
        { id: 3, name: "Accord" },
        { id: 4, name: "CR-V" },
        { id: 5, name: "HR-V" },
        { id: 6, name: "Fit" },
        { id: 7, name: "Pilot" },
    ],
    Chevrolet: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Silverado" },
        { id: 3, name: "Camaro" },
        { id: 4, name: "Onix" },
        { id: 5, name: "Equinox" },
        { id: 6, name: "Tahoe" },
        { id: 7, name: "Trailblazer" },
    ],
    Nissan: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Sentra" },
        { id: 3, name: "Versa" },
        { id: 4, name: "Altima" },
        { id: 5, name: "X-Trail" },
        { id: 6, name: "Kicks" },
        { id: 7, name: "Pathfinder" },
        { id: 8, name: "Frontier" },
    ],
    Hyundai: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Elantra" },
        { id: 3, name: "Sonata" },
        { id: 4, name: "Tucson" },
        { id: 5, name: "Santa Fe" },
        { id: 6, name: "Creta" },
        { id: 7, name: "Kona" },
    ],
    Kia: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Rio" },
        { id: 3, name: "Forte" },
        { id: 4, name: "Sportage" },
        { id: 5, name: "Sorento" },
        { id: 6, name: "Picanto" },
        { id: 7, name: "Seltos" },
    ],
    "Mercedes-Benz": [
        { id: 1, name: "Otro" },
        { id: 2, name: "Clase A" },
        { id: 3, name: "Clase C" },
        { id: 4, name: "Clase E" },
        { id: 5, name: "GLC" },
        { id: 6, name: "GLA" },
        { id: 7, name: "GLE" },
    ],
    BMW: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Serie 3" },
        { id: 3, name: "Serie 5" },
        { id: 4, name: "X3" },
        { id: 5, name: "X5" },
        { id: 6, name: "X1" },
        { id: 7, name: "X7" },
    ],
    Audi: [
        { id: 1, name: "Otro" },
        { id: 2, name: "A3" },
        { id: 3, name: "A4" },
        { id: 4, name: "Q3" },
        { id: 5, name: "Q5" },
        { id: 6, name: "Q7" },
        { id: 7, name: "Q8" },
    ],
    Lexus: [
        { id: 1, name: "Otro" },
        { id: 2, name: "IS" },
        { id: 3, name: "ES" },
        { id: 4, name: "RX" },
        { id: 5, name: "NX" },
        { id: 6, name: "UX" },
        { id: 7, name: "LX" },
    ],
    Tesla: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Model 3" },
        { id: 3, name: "Model Y" },
        { id: 4, name: "Model S" },
        { id: 5, name: "Model X" },
    ],
    Subaru: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Impreza" },
        { id: 3, name: "Forester" },
        { id: 4, name: "Outback" },
        { id: 5, name: "XV" },
        { id: 6, name: "Ascent" },
    ],
    Mazda: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Mazda3" },
        { id: 3, name: "Mazda6" },
        { id: 4, name: "CX-5" },
        { id: 5, name: "CX-30" },
        { id: 6, name: "CX-3" },
        { id: 7, name: "CX-9" },
    ],
    Jeep: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Wrangler" },
        { id: 3, name: "Grand Cherokee" },
        { id: 4, name: "Compass" },
        { id: 5, name: "Renegade" },
        { id: 6, name: "Cherokee" },
        { id: 7, name: "Gladiator" },
    ],
    Volvo: [
        { id: 1, name: "Otro" },
        { id: 2, name: "XC40" },
        { id: 3, name: "XC60" },
        { id: 4, name: "XC90" },
        { id: 5, name: "S60" },
        { id: 6, name: "S90" },
        { id: 7, name: "XC70" },
    ],
    Porsche: [
        { id: 1, name: "Otro" },
        { id: 2, name: "911" },
        { id: 3, name: "Cayenne" },
        { id: 4, name: "Macan" },
        { id: 5, name: "Panamera" },
        { id: 6, name: "Taycan" },
        { id: 7, name: "Boxster" },
    ],
    "Land Rover": [
        { id: 1, name: "Otro" },
        { id: 2, name: "Discovery" },
        { id: 3, name: "Range Rover" },
        { id: 4, name: "Defender" },
        { id: 5, name: "Evoque" },
        { id: 6, name: "Discovery Sport" },
    ],
    Jaguar: [
        { id: 1, name: "Otro" },
        { id: 2, name: "XE" },
        { id: 3, name: "XF" },
        { id: 4, name: "F-Pace" },
        { id: 5, name: "E-Pace" },
    ],
    Peugeot: [
        { id: 1, name: "Otro" },
        { id: 2, name: "208" },
        { id: 3, name: "3008" },
        { id: 4, name: "2008" },
        { id: 5, name: "5008" },
        { id: 6, name: "301" },
        { id: 7, name: "308" },
    ],
    Renault: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Clio" },
        { id: 3, name: "Megane" },
        { id: 4, name: "Duster" },
        { id: 5, name: "Koleos" },
        { id: 6, name: "Logan" },
        { id: 7, name: "Sandero" },
        { id: 8, name: "Captur" },
    ],
    Fiat: [
        { id: 1, name: "Otro" },
        { id: 2, name: "500" },
        { id: 3, name: "Panda" },
        { id: 4, name: "Tipo" },
        { id: 5, name: "Pulse" },
        { id: 6, name: "Cronos" },
        { id: 7, name: "Argo" },
        { id: 8, name: "Strada" },
    ],
    Citroen: [
        { id: 1, name: "Otro" },
        { id: 2, name: "C3" },
        { id: 3, name: "C4" },
        { id: 4, name: "C5 Aircross" },
        { id: 5, name: "Berlingo" },
    ],
    Mitsubishi: [
        { id: 1, name: "Otro" },
        { id: 2, name: "L200" },
        { id: 3, name: "Outlander" },
        { id: 4, name: "Eclipse Cross" },
        { id: 5, name: "ASX" },
        { id: 6, name: "Montero" },
        { id: 7, name: "Outlander Sport" },
    ],
    Suzuki: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Swift" },
        { id: 3, name: "Vitara" },
        { id: 4, name: "Jimny" },
        { id: 5, name: "Baleno" },
        { id: 6, name: "S-Cross" },
        { id: 7, name: "Ertiga" },
    ],
    GMC: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Sierra" },
        { id: 3, name: "Terrain" },
        { id: 4, name: "Acadia" },
        { id: 5, name: "Yukon" },
    ],
    Cadillac: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Escalade" },
        { id: 3, name: "XT5" },
        { id: 4, name: "XT4" },
        { id: 5, name: "CT5" },
    ],
    Ram: [
        { id: 1, name: "Otro" },
        { id: 2, name: "1500" },
        { id: 3, name: "2500" },
        { id: 4, name: "3500" },
        { id: 5, name: "ProMaster" },
        { id: 6, name: "TRX" },
    ],
    Acura: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Integra" },
        { id: 3, name: "TLX" },
        { id: 4, name: "RDX" },
        { id: 5, name: "MDX" },
        { id: 6, name: "NSX" },
    ],
    Infiniti: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Q50" },
        { id: 3, name: "QX50" },
        { id: 4, name: "QX60" },
        { id: 5, name: "Q60" },
        { id: 6, name: "QX80" },
    ],
    Mini: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Cooper" },
        { id: 3, name: "Countryman" },
        { id: 4, name: "Clubman" },
        { id: 5, name: "Paceman" },
    ],
    "Alfa Romeo": [
        { id: 1, name: "Otro" },
        { id: 2, name: "Giulia" },
        { id: 3, name: "Stelvio" },
        { id: 4, name: "Tonale" },
        { id: 5, name: "Giulietta" },
        { id: 6, name: "4C" },
    ],
    Dodge: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Charger" },
        { id: 3, name: "Challenger" },
        { id: 4, name: "Durango" },
        { id: 5, name: "Journey" },
        { id: 6, name: "Hornet" },
    ],
    Chrysler: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Pacifica" },
        { id: 3, name: "300" },
        { id: 4, name: "Voyager" },
    ],
    Buick: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Enclave" },
        { id: 3, name: "Encore" },
        { id: 4, name: "Envision" },
    ],
    Skoda: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Octavia" },
        { id: 3, name: "Superb" },
        { id: 4, name: "Kodiaq" },
        { id: 5, name: "Karoq" },
    ],
    SEAT: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Ibiza" },
        { id: 3, name: "Leon" },
        { id: 4, name: "Arona" },
        { id: 5, name: "Ateca" },
    ],
    Toyota: [
        { id: 1, name: "Otro" },
        { id: 2, name: "Corolla" },
        { id: 3, name: "Camry" },
        { id: 4, name: "RAV4" },
        { id: 5, name: "Hilux" },
        { id: 6, name: "Fortuner" },
    ],
};

