export const PATHS = {
    login: "/login",
    registerUser: "/register-user",
    recoveryPassword: "/recovery-password",
    verifyEmail: "/verify-email",
    vehicles: "/vehicles",
    maintenance: "/maintenance",
    maintenanceCreate: "/maintenance/create",
    workshops: "/workshops",
    uploadLogoWorkshop: "/upload-logo-workshop",
    adventure: "/adventure",
    userInformation: "/user-information",
    testImages: "/test-images",
    home: "/",
    error404: "*",
}